#!/bin/bash


echo "Repository: https://bit.ly/3mfe5e5"
echo "Usage: bash gdown filename.extension fileid"

fileNAME=$1
fileID=$2

echo -n $fileNAME > /tmp/name
echo -n $fileID > /tmp/id
[ -s /tmp/name ] || echo Missing File NAME
[ -s /tmp/id ] || echo Missing File ID



echo "Google Drive download via curl"
echo "File NAME: $fileNAME"
echo "File ID: $fileID"
echo "Downloading..."

rm -rf /tmp/cookies.txt
confirmCode=$(curl -skLc /tmp/cookies.txt "https://docs.google.com/uc?export=download&id=$fileID" | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p');
curl -kLb /tmp/cookies.txt -o $fileNAME "https://docs.google.com/uc?export=download&confirm=$confirmCode&id=$fileID"
